### ISSUE TITLE
Peer to Peer Code review.

### ISSUE THREAD

**Issue by wadaudzai** [mohamedSabry0/leaderboard#4]
Dear Mohamed,

Your code looks awesome we would like to still add a few things that we think would be good for this project. 
- Please try to add a more descriptive README.md file.
- Please try to give us a live demo link of your website in the README.md file.
- It would be more descriptive to use comments in specific parts of the code to help the reviewer of the code better understand the functions and other components of the project.

Regards,

**Comment by mohamedSabry0** [comment]
Thank you for the suggestions 👍 I'll look into these and implement them ASAP.
